site_name: Guides for Online Learning Tools at University of York, UK
site_author: University of York
copyright: <a href="/help/site-index">Site index</a> | Copyright &copy; 2024 University of York, UK | <a href="https://www.york.ac.uk/about/legal-statements/#tab-1">Legal statements</a>


theme:
  name: material
  custom_dir: overrides
  font:
    text: Inter
  icon:
    logo: material/home-circle
    tag:
      KeyGuideTeaching: simple/go
      KeyGuideAdmin: simple/go
      Accessibility: octicons/accessibility-inset-16
      Assessment: octicons/check-circle-16
      Communication: octicons/megaphone-16
      InteractiveContent: material/cursor-default-click-outline
      Training: material/school
      Help: material/help-circle-outline
      Ultra: material/laptop
      Panopto: fontawesome/solid/video
      OtherTools: material/toolbox
  # favicon: img/favicon.jpg
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom #UoY branding - dark blue
      accent: custom #UoY branding - light blue
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey #UoY branding-ish
      accent: yellow #UoY branding-ish
      toggle: 
        icon: material/brightness-7
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.path
    # - navigation.expand
    # - navigation.sections
    - navigation.top
    - navigation.tracking
    # - toc.integrate

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: false
      title: On this page

nav:
  # - Home: https://vle-support.york.ac.uk/
  - Testing: testing.md
  - Learn Ultra VLE:
    - ultra/index.md
    - Getting started with Ultra:
      - VLE site design principles: ultra/site-design-principles.md
      - Site readiness checklist: ultra/site-readiness-checklist.md
      - Access your sites: ultra/access-sites.md
      - Notifications: ultra/notifications.md
      - Troubleshooting common issues: help/troubleshooting.md
    - Site structure & design:
      - Navigate Ultra sites: ultra/navigate-ultra-site.md
      - Use the Ultra template: ultra/ultra-template.md
      - Personalise site design: ultra/personalise-site-design.md
      - Folders & Learning Modules: ultra/folder-learning-module.md
      - Course image (site banner): ultra/course-image.md
      - Course staff: ultra/course-staff.md
      - Site renames: ultra/site-rename.md
    - Content creation:
      # - I want to...: #MAKE PAGE
      - Documents | pages: ultra/documents.md
      - Images: ultra/images.md
      - Upload Files: ultra/files.md
      - Links: ultra/links.md
      - Video | Panopto: panopto/embed-panopto-ultra.md
      - Video | YouTube: ultra/youtube.md
      - Embed content: ultra/embedded-content.md
      - HTML objects: ultra/html-objects.md
      - Maths content: ultra/maths.md
      - Assignment | set up: ultra/assignment-set-up.md
      - Assignment | marking: ultra/assignment-marking.md
      - Test | quizzes & exams: ultra/test.md
      - Form | survey: ultra/form.md
      - Journal | reflection: ultra/journal.md
      - Gradebook: ultra/gradebook.md
      - Accessible Ultra content: accessibility/accessible-ultra-content.md
    - Content management:
      - Content visibility: ultra/content-visibility.md
      - Release conditions: ultra/release-conditions.md
      - Edit, move & delete content: ultra/edit-delete-move-content.md
      - Batch edit: ultra/batch-edit.md
      - Copy content: ultra/copy-content.md
      - Manage content in shared sites: ultra/content-shared-sites.md
    - Communication & interaction:
      - Announcements: ultra/announcements.md
      - Facilitate groupwork: ultra/groupwork.md #MAKE PAGE - WHERE TO GO?
      - Course Groups: ultra/course-groups.md
      - Discussions: ultra/discussions.md
      - Messages: ultra/messages-tool.md
      - Notifications: ultra/notifications.md
    - Site access & users: 
      - Site availability: ultra/site-availability.md
      - Course roles: ultra/course-roles.md
      - Enrol a user: ultra/enrol-user.md
      - Enrol a cohort/group: ultra/enrol-cohort.md
      - Unenrol a user: ultra/unenrol-user.md
      - External users: ultra/external-users.md
  - Panopto Videos:
    - panopto/index.md
    - Getting Started with Panopto: 
      # - Quick Start Lecturer Guide:
      - Logging into the Panopto Cloud: panopto/logging-into-panopto.md
      # - Creating a Manual Recording (Windows): panopto/manual-recording-win.md
      # - Creating a Manual Recording (Mac): panopto/manual-recording-mac.md
      # - Making a Recording via Web Browser (Panopto Capture): panopto/panopto-capture.md
      - Copying a Recording: panopto/copy-recording.md
      # - Moving a Recording: panopto/move-recording.md
      - Editing Panopto videos (basic edits): panopto/panopto-basic-editing.md
      # - Sharing a Recording: panopto/sharing-recordings.md
      - Using Replay in teaching rooms: panopto/lecture-capture.md
    - Managing Video Content: 
      - Reusing Module Media: panopto/reusing-module-media.md
      # - Panopto Captions: panopto/captioning.md
      # - Panopto Video Assessments: panopto/panopto-vid-assessment.md
      # - Changing Video Availability: panopto/change-availability.md
      - Embedding a Panopto video in Blackboard Ultra: panopto/embed-panopto-ultra.md
    - Advanced Editing: 
      # - Adding Quizzes: panopto/adding-quizzes.md
      - Adding Presentation Slides: panopto/add-presentation.md
      # - Adding Table of Contents and Using Smart Chapters: panopto/table-of-contentsx.md
      # - Adding Additional Streams: panopto/addstreams.md
    - Assessment submissions: panopto/submissions.md
  - Accessibility:
    - accessibility/index.md
    - Ally accessibility checker: accessibility/ally-accessibility-checker.md
    - Accessible Ultra content: accessibility/accessible-ultra-content.md
    - Accessible maths: accessibility/accessible-maths.md
  - Assessment:
    - assessment/index.md
    - Which assessment tool?: assessment/which-assessment-tool.md
    - TurnItIn Feedback Studio:
      - assessment/tfs/index.md
      - TFS | set up: assessment/tfs/set-up.md
      - TFS | marking: assessment/tfs/marking.md
      - TFS & E:Vision | release feedback & marks: assessment/tfs/feedback-marks.md
    - Ultra assessment tools:
      - Ultra Assignment | set up: ultra/assignment-set-up.md
      - Ultra Assignment | marking: ultra/assignment-marking.md
      - Ultra Test | quizzes & exams: ultra/test.md
      - Ultra Journal: ultra/journal.md
      - Ultra Gradebook: ultra/gradebook.md
      - Ultra releasing marks & feedback: assessment/ultra-release-marks.md
    - Panopto assessment submissions: panopto/submissions.md
    - Group assignments: assessment/group-assignment.md
    - Assessed presentations: assessment/presentations.md
    - Assessment & LoA: assessment/assessment-loa.md
    - Anon Assign end of life: assessment/anonymous-assignment-eol.md
    - Staff assessment training: assessment/trainingassessment.md
  - Other Tools:
    - other-tools/index.md
    - Tools at a glance: https://bit.ly/yorktools
    - Canvas VLE: other-tools/canvas.md
    - Mentimeter | polling: 
      - Overview: other-tools/mentimeter.md
      - Logging in to Mentimeter: other-tools/mentimeter-logging-in.md
      - Creating a  presentation: other-tools/mentimeter-creating-a-presentation.md
      - Closed questions: other-tools/mentimeter-closed-question-types.md
      - Open questions: other-tools/mentimeter-open-question-types.md
      - Q&A and comments: other-tools/mentimeter-q_and_a-comments.md
      - Other question types: other-tools/mentimeter-other-question-types.md
      - Content slides: other-tools/mentimeter-content-slides.md
      - University templates: other-tools/mentimeter-university-themes.md
      - Presenting with Mentimeter: other-tools/mentimeter-presenting.md
      - Safe anonymity: other-tools/mentimeter-safe-anonymity.md
    - Padlet (pinboards):
      - Getting started with Padlet: other-tools/padlet.md
      - Padlet - alternative to Ultra discussions: other-tools/padlet-discussion-alternative.md
    - Reading List: other-tools/reading-list.md
    - System data & analytics: other-tools/analytics.md
    - Xerte | interactive content: other-tools/xerte.md
  - Training: #SECTION NEEDS FINALISING
    - training/index.md
    - Workshops | learn skills: 
      - Training | Ultra Essentials: training/ultra-essentials.md
    - Webinars | share practice: training/webinars.md
    - CMALT | professional development: training/cmalt.md
        # - VLE Ultra training: #RETIRE/MOVE MOST
    #   - Workshop calendar: ultra/workshop-calendar.md
    #   - Workshop - Ultra Essentials (teaching): ultra/workshop-ultra-essentials-teaching.md
    #   # - Workshop - Ultra Essentials (admin): ultra/workshop-ultra-essentials-admin.md
    #   - Workshops - Ultra Bitesize: ultra/workshop-ultra-bitesize.md
    #   # - Workshops - Ultra Drop-ins: ultra/workshop-ultra-drop-ins.md
    #   - Workshops - General Ultra and Turnitin Marker Support Drop-ins: ultra/workshop-turnitin-marker-support.md
  - Help:
    - help/index.md
    - Troubleshooting common issues: help/troubleshooting.md
    - News: help/news.md
    - System updates & issues: help/updates-issues.md
    - Contact us: help/contact-us.md
    - Taking screenshots: help/screenshots.md
    - Finding Usernames: help/usernames.md
    - Finding YCodes: help/ycodes.md
    - International access: help/international-access.md
    - Site index: help/site-index.md
  
extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/UoYVLE
      name: DET on Twitter (X)
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/uoyvle/
      name: DET on Instagram
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCNRdi4ySV6gnXOojwv-xa5g
      name: DET on YouTube
    - icon: fontawesome/solid/paper-plane
      link: mailto:vle-support@york.ac.uk
      name: Contact Support Desk
  tags:
    Key guide - teaching: KeyGuideTeaching
    Key guide - admin: KeyGuideAdmin
    Accessibility: Accessibility
    Assessment: Assessment
    Communication: Communication
    Interactive content: InteractiveContent
    Training: Training
    Help: Help
    Ultra: Ultra
    Panopto: Panopto
    Other tools: OtherTools
  analytics:
    provider: google
    property: G-Q6B3RZT1K0

extra_css:
  - css/extra.css

extra_javascript:
  - javascripts/extra.js

plugins:
  - redirects:
      redirect_maps:
        'ultra/add-learning-module-image.md': 'ultra/folder-learning-module.md'
        'ultra/adding-html.md': 'ultra/html-objects.md'
        'ultra/groups.md': 'ultra/course-groups.md'
        'ultra/workshop-ultra-essentials-teaching.md': 'training/ultra-essentials.md'
        'ultra/international-access.md': 'help/international-access.md'
        'contact-us/index.md': 'help/contact-us.md'
        'updates/index.md': 'help/updates-issues.md'
        'updates/suggestions.md': 'help/contact-us.md'
        'contact-us/usernames.md': 'help/usernames.md'
        'contact-us/ycodes.md': 'help/ycodes.md'
        'contact-us/screenshots.md': 'help/screenshots.md'
        'tags-index.md': 'help/site-index.md'
        'eassessment/ultraassignment.md': 'ultra/assignment-set-up.md'
        'eassessment/ultratest.md': 'ultra/test.md'
        'eassessment/turnitinfeedbackstudio.md': 'assessment/tfs/index.md'
        'eassessment/anonassigneol.md': 'assessment/anonymous-assignment-eol.md'
        'othertools/index.md': 'other-tools/index.md'
        'canvas/index.md': 'other-tools/canvas.md'
        'mentimeter/index.md': 'other-tools/mentimeter.md'
        'padlet/index.md': 'other-tools/padlet.md'
        'padlet/padlet-discussion-alternative.md': 'other-tools/padlet-discussion-alternative.md'
        'readinglist/index.md': 'other-tools/reading-list.md'
        'xerte/index.md': 'other-tools/xerte.md'
        'system-data-and-analytics/index.md': 'other-tools/analytics.md'
  - search
  - tags:
      tags_file: help/site-index.md
      tags_allowed:
        - Key guide - teaching
        - Key guide - admin
        - Accessibility
        - Assessment
        - Communication
        - Interactive content
        - Training
        - Help
        - Ultra
        - Panopto
        - Other tools

watch:
- overrides