name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      # install dependencies
      - run: pip install mkdocs-material
      - run: pip install mkdocs-redirects
      # STUDENT SITE
      # build student site into subfolder
      # - run: python scripts/pre-run-student.py
      # - run: mkdocs build -f mkdocs-student.yml -d site/student
      # # STAFF SITE 
      # # run python pre-build script
      # - run: python scripts/pre-run-staff.py
      # # build staff site into main output folder ('site')
      # - run: mkdocs build -f mkdoc-staff.yml -d site
      # deploy final combined site
      - run: mkdocs gh-deploy --force